import typing, abc
from System import IEquatable_1, Array_1, ValueTuple_2
from PalmSens.Sdk.Data.Models.Domain.Values import AxisDataTypeVariant, DataValueTypeVariant
from PalmSens.Sdk.Data.Models.Domain import CustomUnit, TechniqueAbbreviation, TechniqueCategory, TechniqueNumber
from System.Collections.Generic import IReadOnlyList_1

class AxisDataType(IEquatable_1[AxisDataType]):
    def __init__(self, variant: AxisDataTypeVariant, customUnit: CustomUnit = ..., customScaleFactor: typing.Optional[float] = ...) -> None: ...
    @property
    def CustomScaleFactor(self) -> typing.Optional[float]: ...
    @property
    def CustomUnit(self) -> CustomUnit: ...
    @property
    def ScaleFactor(self) -> float: ...
    @property
    def Variant(self) -> AxisDataTypeVariant: ...
    def Clone(self) -> AxisDataType: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: AxisDataType, right: AxisDataType) -> bool: ...
    def __ne__(self, left: AxisDataType, right: AxisDataType) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: AxisDataType) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class GroupId(abc.ABC):
    ACVoltammetry : str
    Advanced : str
    AppliedCurrent : str
    BiPot : str
    Cell : str
    Chronoamperometry : str
    Chronocoulometry : str
    Chronopotentiometry : str
    ConstantCurrentStage : str
    ConstantPotentialStage : str
    CurrentRange : str
    Curve : str
    CyclicVoltammetry : str
    DifferentialPulseVoltammetry : str
    ElectrochemicalImpedanceSpectroscopy : str
    FastAmperometry : str
    GalvanostaticImpedanceSpectroscopy : str
    HardwareSync : str
    InstrumentSpecific : str
    Level : str
    LinearSweepPotentiometry : str
    LinearSweepVoltammetry : str
    ManualControl : str
    MetaDataTags : str
    Method : str
    MethodScriptSandbox : str
    MixedMode : str
    MultiplePulseAmperometry : str
    MultiStepAmperometry : str
    MultiStepPotentiometry : str
    NormalPulseVoltammetry : str
    OCPSettings : str
    OpenCircuitPotentiometry : str
    OpenCircuitStage : str
    PeaksAndLevels : str
    Peripherals : str
    Plotting : str
    PostMeasurement : str
    PostProcessing : str
    PotentialRange : str
    Pretreatment : str
    PulsedAmperometricDetection : str
    RecordAdditionalData : str
    Smoothing : str
    SquareWaveVoltammetry : str
    Step : str
    StrippingChronopotentiometry : str
    SweepPotentialStage : str
    TagConcentration : str
    TagSurfaceArea : str
    Triggers : str


class ParameterId(abc.ABC):
    AbortCurrentLimit : str
    ACCurrent : str
    AddTag : str
    Amplitude : str
    AnalogIn : str
    AnalogOut : str
    Analyte : str
    AppliedCurrent : str
    AppliedCurrentRange : str
    AppliedCurrentVersusPrevious : str
    ApplyPeakDetection : str
    ApplySmoothing : str
    AutoGeneratedByExtraValue : str
    BeginCurrent : str
    BeginPotential : str
    BeginPotentialVersusPrevious : str
    BiPotCurrentRange : str
    BiPotMode : str
    BiPotOn : str
    BiPotPotential : str
    CellControl : str
    CellCurrentRange : str
    CellModeAfterMeasurement : str
    CellOn : str
    CellOnAfterMeasurement : str
    CellPotential : str
    Celltype : str
    ChargeLimit : str
    Concentration : str
    ConditioningPotential : str
    ConditioningTime : str
    CurrentAfterMeasurement : str
    CurrentAfterMeasurementRange : str
    CurrentLimit : str
    CurrentRange : str
    CurveName : str
    Curves : str
    DCCurrent : str
    DepositionPotential : str
    DepositionTime : str
    EISFrequencyType : str
    EISScanType : str
    EnableDropDetection : str
    EnableHardwareSync : str
    EnableOcp : str
    EndCurrent : str
    EndPotential : str
    EndPotentialVersusPrevious : str
    EquilibrationPotential : str
    EquilibrationTime : str
    Frequency : str
    IntervalTime : str
    IRCompensation : str
    IsSlaveChannel : str
    Labels : str
    Levels : str
    Maximum : str
    MaximumAbortCurrentLimit : str
    MaximumChargeLimit : str
    MaximumCurrentLimit : str
    MaximumCurrentRange : str
    MaximumEquilibrationTime : str
    MaximumFrequency : str
    MaximumOCPTime : str
    MaximumPotentialLimit : str
    MaximumPotentialRange : str
    MaximumTemperatureLimit : str
    Measure : str
    MeasureAuxiliaryInput : str
    MeasureCellPotential : str
    MeasureCurrentForwardReverse : str
    MeasureDCCurrent : str
    MeasuredCurrentRange : str
    MeasuredCurrentRangeAfterMeasurement : str
    MeasuredPotentialRangeAfterMeasurement : str
    MeasurementTime : str
    MeasureWECurrent : str
    MeasureWEPotential : str
    MetaDataTags : str
    Minimum : str
    MinimumAbortCurrentLimit : str
    MinimumChargeLimit : str
    MinimumCurrentLimit : str
    MinimumCurrentRange : str
    MinimumFrequency : str
    MinimumPeakHeight : str
    MinimumPeakWidth : str
    MinimumPotentialLimit : str
    MinimumPotentialRange : str
    MinimumPotentialRateLimit : str
    MinimumSamplingTime : str
    MinimumTemperatureLimit : str
    Name : str
    NewTag : str
    Notes : str
    NumberOfCycles : str
    NumberOfFrequencies : str
    NumberOfFrequenciesPerDecade : str
    NumberOfScans : str
    OCP : str
    OCPStabilityCriterion : str
    Options : str
    PADMode : str
    PerDecade : str
    PGAGain : str
    Potential : str
    Potential1 : str
    Potential2 : str
    Potential3 : str
    PotentialAfterMeasurement : str
    PotentialAlternatingCurrent : str
    PotentialDirectCurrent : str
    PotentialLimit : str
    PotentialRange : str
    PotentialRateLimit : str
    PotentialVersusPrevious : str
    PulsePotential : str
    PulseTime : str
    Range : str
    RecordLevel : str
    RecordTimeDomainData : str
    RunTime : str
    ScanRate : str
    Script : str
    SelectLimitPerLevel : str
    SelectRecordPerLevel : str
    SelectTriggerPerLevel : str
    SineWaveAmplitude : str
    SmoothingLevel : str
    Stages : str
    StandbyTime : str
    Starting : str
    StartingCurrentRange : str
    StartingPotentialRange : str
    StepCurrent : str
    StepPotential : str
    Steps : str
    StirrerOn : str
    StoreTimeDomainData : str
    SurfaceArea : str
    TemperatureLimit : str
    Time1 : str
    Time2 : str
    Time3 : str
    TriggerDelayPeriod : str
    TriggerOnDelay : str
    TriggerOnEquilibration : str
    TriggerOnStart : str
    Use : str
    UseCurrentAfterMeasurement : str
    UseIRCompensation : str
    UseMaximumAbortCurrentLimit : str
    UseMaximumChargeLimit : str
    UseMaximumCurrentLimit : str
    UseMaximumPotentialLimit : str
    UseMaximumTemperatureLimit : str
    UseMeasuredCurrentRangeAfterMeasurement : str
    UseMeasuredPotentialRangeAfterMeasurement : str
    UseMinimumAbortCurrentLimit : str
    UseMinimumChargeLimit : str
    UseMinimumCurrentLimit : str
    UseMinimumPotentialLimit : str
    UseMinimumPotentialRateLimit : str
    UseMinimumTemperatureLimit : str
    UsePotentialAfterMeasurement : str
    VersusPrevious : str
    Vertex1Potential : str
    Vertex2Potential : str
    WindowSize : str
    XAxis : str
    YAxis : str
    @classmethod
    @property
    def ExtraValues(cls) -> Array_1[str]: ...
    @classmethod
    @property
    def Limits(cls) -> Array_1[str]: ...
    @staticmethod
    def IsExtraValue(parameterId: str) -> bool: ...


class Prefix(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...

    # Values:
    None_ : Prefix # 0
    Deca : Prefix # 1
    Hecto : Prefix # 2
    Kilo : Prefix # 3
    Mega : Prefix # 6
    Giga : Prefix # 9
    Tera : Prefix # 12
    Peta : Prefix # 15
    Exa : Prefix # 18
    Zetta : Prefix # 21
    Yotta : Prefix # 24
    Ronna : Prefix # 27
    Quetta : Prefix # 30
    Quecto : Prefix # -30
    Ronto : Prefix # -27
    Yocto : Prefix # -24
    Zepto : Prefix # -21
    Atto : Prefix # -18
    Femto : Prefix # -15
    Pico : Prefix # -12
    Nano : Prefix # -9
    Micro : Prefix # -6
    Milli : Prefix # -3
    Centi : Prefix # -2
    Deci : Prefix # -1


class Quantity(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...

    # Values:
    Capacitance : Quantity # 0
    Charge : Quantity # 1
    Conductance : Quantity # 2
    Current : Quantity # 3
    Frequency : Quantity # 4
    Potential : Quantity # 5
    Resistance : Quantity # 6
    Time : Quantity # 7
    Temperature : Quantity # 8
    Ordinal : Quantity # 9
    Angle : Quantity # 10
    Percentage : Quantity # 11
    TimePerPotential : Quantity # 12
    PotentialPerTime : Quantity # 13
    Custom : Quantity # 14


class TechniqueId(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...

    # Values:
    LinearSweepVoltammetry : TechniqueId # 0
    CyclicVoltammetry : TechniqueId # 1
    FastCyclicVoltammetry : TechniqueId # 2
    ACVoltammetry : TechniqueId # 3
    DifferentialPulseVoltammetry : TechniqueId # 4
    SquareWaveVoltammetry : TechniqueId # 5
    NormalPulseVoltammetry : TechniqueId # 6
    Chronoamperometry : TechniqueId # 7
    MultiStepAmperometry : TechniqueId # 8
    FastAmperometry : TechniqueId # 9
    PulsedAmperometricDetection : TechniqueId # 10
    MultiplePulseAmperometry : TechniqueId # 11
    OpenCircuitPotentiometry : TechniqueId # 12
    Chronopotentiometry : TechniqueId # 13
    MultiStepPotentiometry : TechniqueId # 15
    LinearSweepPotentiometry : TechniqueId # 16
    StrippingChronopotentiometry : TechniqueId # 17
    Chronocoulometry : TechniqueId # 18
    ElectrochemicalImpedanceSpectroscopy : TechniqueId # 19
    GalvanostaticImpedanceSpectroscopy : TechniqueId # 21
    MixedMode : TechniqueId # 23
    MethodScriptSandbox : TechniqueId # 24
    CorrosionPotential : TechniqueId # 25
    CyclicPolarization : TechniqueId # 26
    GalvanostaticDetection : TechniqueId # 27
    LinearPolarization : TechniqueId # 28
    PotentiostaticDetection : TechniqueId # 29


class TechniqueIdExtensions(abc.ABC):
    @staticmethod
    def GetAbbreviation(technique: TechniqueId) -> TechniqueAbbreviation: ...
    @staticmethod
    def GetCategory(technique: TechniqueId) -> TechniqueCategory: ...
    @staticmethod
    def GetDefaultAxesTypes(technique: TechniqueId) -> IReadOnlyList_1[ValueTuple_2[DataValueTypeVariant, DataValueTypeVariant]]: ...
    @staticmethod
    def GetDefaultCurveName(technique: TechniqueId) -> str: ...
    @staticmethod
    def GetDefaultXAxisDataValueTypeVariantForExtraValue(technique: TechniqueId, extraValueParameterId: str) -> DataValueTypeVariant: ...
    @staticmethod
    def GetDefaultYAxisDataValueTypeVariantsForExtraValue(technique: TechniqueId, extraValueParameterId: str) -> Array_1[DataValueTypeVariant]: ...
    @staticmethod
    def HasAuxiliary(technique: TechniqueId) -> bool: ...
    @staticmethod
    def HasCharge(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsAmperometric(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsCoulometric(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsFast(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsGalvanostatic(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsImpedimetric(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsLinearSweep(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsMultiScan(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsMultiStep(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsPotentiometric(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsPulsed(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsTimeMethod(technique: TechniqueId) -> bool: ...
    @staticmethod
    def IsVoltammetric(technique: TechniqueId) -> bool: ...
    @staticmethod
    def SupportsBiPot(technique: TechniqueId) -> bool: ...
    @staticmethod
    def SupportsHardwareSync(technique: TechniqueId) -> bool: ...
    @staticmethod
    def ToTechniqueNumber(technique: TechniqueId) -> TechniqueNumber: ...


class TimeUnitType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...

    # Values:
    None_ : TimeUnitType # 0
    Second : TimeUnitType # 1
    Minute : TimeUnitType # 2
    Hour : TimeUnitType # 3
    Day : TimeUnitType # 4
    Week : TimeUnitType # 5
    Year : TimeUnitType # 6
