#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PalmSens.Core.Simplified.Android.Resource", IsApplication=false)]

namespace PalmSens.Core.Simplified.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int autoScaleTextStyleView = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int minTextSize = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public static int background_grey = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int background_lightgrey = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int background_lightgrey_down = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int black = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int palmsensblue = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int white = 2130837509;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public static int ic_menu_connect = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int ic_menu_connected = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int pstouch_button = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int pstouch_button_container = 2130903043;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public static int button_scan = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int new_devices = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int paired_devices = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int scan = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int title_new_devices = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int title_paired_devices = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public static int device_list = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int device_name = 2131034113;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public static int bluetooth_option_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public static int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7F070002
			public static int bt_not_enabled_leaving = 2131165186;
			
			// aapt resource value: 0x7F070003
			public static int button_scan = 2131165187;
			
			// aapt resource value: 0x7F070004
			public static int connect = 2131165188;
			
			// aapt resource value: 0x7F070005
			public static int discoverable = 2131165189;
			
			// aapt resource value: 0x7F070001
			public static int Hello = 2131165185;
			
			// aapt resource value: 0x7F070006
			public static int none_found = 2131165190;
			
			// aapt resource value: 0x7F070007
			public static int none_paired = 2131165191;
			
			// aapt resource value: 0x7F070008
			public static int not_connected = 2131165192;
			
			// aapt resource value: 0x7F070009
			public static int scanning = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public static int select_device = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public static int send = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public static int title_connected_to = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public static int title_connecting = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public static int title_not_connected = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public static int title_other_devices = 2131165199;
			
			// aapt resource value: 0x7F070010
			public static int title_paired_devices = 2131165200;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public static int BlueToothTheme = 2131230720;
			
			// aapt resource value: 0x7F080001
			public static int BlueToothTheme_ButtonStyle = 2131230721;
			
			// aapt resource value: 0x7F080002
			public static int BlueToothTheme_ListViewStyle = 2131230722;
			
			// aapt resource value: 0x7F080003
			public static int BlueToothTheme_TextStyle = 2131230723;
			
			// aapt resource value: 0x7F080004
			public static int BlueToothTheme_TitleTextStyle = 2131230724;
			
			// aapt resource value: 0x7F080005
			public static int BlueToothTheme_WindowTitleBackground = 2131230725;
			
			// aapt resource value: 0x7F080006
			public static int BlueToothTheme_WindowTitleStyle = 2131230726;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010001 }
			public static int[] AutoScaleTextView = new int[] {
					2130771969};
			
			// aapt resource value: 0
			public static int AutoScaleTextView_minTextSize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
