import typing
from System import IAsyncDisposable, Uri, Func_2, Guid, Func_1
from System.Collections.Generic import IReadOnlyList_1
from PalmSens.Sdk.Lablink.Example.Lablink.Models import LablinkInstrumentInfo, LablinkInfo
from System.Threading.Tasks import Task_1, ValueTask, Task
from System.Threading import CancellationToken
from PalmSens.Sdk.Lablink.Example.Lablink.Clients import LablinkHttpClient
from Microsoft.AspNetCore.SignalR.Client import HubConnection
from PalmSens.Sdk.Lablink.Example.Lablink.Models.Data import MeasurementInfo, LablinkMeasurement
from PalmSens import Method

class Lablink(IAsyncDisposable):
    @property
    def Address(self) -> Uri: ...
    @property
    def Instruments(self) -> IReadOnlyList_1[LablinkInstrumentInfo]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Serial(self) -> str: ...
    def ConnectInstruments(self, instruments: IReadOnlyList_1[LablinkInstrumentInfo], cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[LablinkInstrument]]: ...
    @staticmethod
    def Create(lablinkInfo: LablinkInfo, client: LablinkHttpClient, hubConnection: HubConnection, instrumentHubConnectionFactory: Func_2[str, HubConnection], cancellationToken: CancellationToken = ...) -> Task_1[Lablink]: ...
    @staticmethod
    def Discover(cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[LablinkInfo]]: ...
    def DiscoverInstruments(self, cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[LablinkInstrumentInfo]]: ...
    def DisposeAsync(self) -> ValueTask: ...
    def GetMeasurements(self, cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[MeasurementInfo]]: ...
    def OnInstrumentInfoChanged(self) -> None: ...
    def StartMeasurements(self, instruments: IReadOnlyList_1[LablinkInstrument], method: Method, cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[LablinkMeasurement]]: ...
    # Skipped GetMeasurement due to it being static, abstract and generic.

    GetMeasurement : GetMeasurement_MethodGroup
    class GetMeasurement_MethodGroup:
        @typing.overload
        def __call__(self, id: Guid, cancellationToken: CancellationToken = ...) -> Task_1[LablinkMeasurement]:...
        @typing.overload
        def __call__(self, info: MeasurementInfo, cancellationToken: CancellationToken = ...) -> Task_1[LablinkMeasurement]:...



class LablinkInstrument(IAsyncDisposable):
    MeasurementFinished : Func_1[Task]
    MeasurementStarted : Func_1[Task]
    @property
    def Parent(self) -> Lablink: ...
    @property
    def Serial(self) -> str: ...
    @staticmethod
    def Create(instrumentInfo: LablinkInstrumentInfo, hubConnection: HubConnection, parent: Lablink, cancellationToken: CancellationToken = ...) -> Task_1[LablinkInstrument]: ...
    def DisposeAsync(self) -> ValueTask: ...
