import typing
from System import Guid, DateTime, DateTimeOffset
from PalmSens.Sdk.Lablink.Example.Lablink.Models.Dtos import DataValueTypes
from System.Collections.Generic import IReadOnlyList_1, Dictionary_2, List_1, IReadOnlyCollection_1, KeyValuePair_2, IEqualityComparer_1
from PalmSens.Sdk.Lablink.Example.Lablink.Models import LablinkInstrumentInfo
from PalmSens.Sdk.Lablink.Example.Lablink.Models.Dtos.SignalR import InstrumentSerialDto
from PalmSens import CurrentRange, Method

class ApiKeyDto(UserCredentialDto):
    def __init__(self) -> None: ...
    @property
    def Password(self) -> str: ...
    @Password.setter
    def Password(self, value: str) -> str: ...
    @property
    def UserName(self) -> str: ...
    @UserName.setter
    def UserName(self, value: str) -> str: ...


class ApiKeyResponseDto:
    def __init__(self) -> None: ...
    @property
    def Token(self) -> str: ...
    @Token.setter
    def Token(self, value: str) -> str: ...
    @property
    def UserName(self) -> str: ...
    @UserName.setter
    def UserName(self, value: str) -> str: ...


class DataArrayResponseDto:
    def __init__(self) -> None: ...
    @property
    def DataArraySizeInBytes(self) -> int: ...
    @DataArraySizeInBytes.setter
    def DataArraySizeInBytes(self, value: int) -> int: ...
    @property
    def DataValuesId(self) -> Guid: ...
    @DataValuesId.setter
    def DataValuesId(self, value: Guid) -> Guid: ...
    @property
    def DataValueType(self) -> DataValueTypes: ...
    @DataValueType.setter
    def DataValueType(self, value: DataValueTypes) -> DataValueTypes: ...


class EmptyDto:
    def __init__(self) -> None: ...


class GetInfoResponseDto:
    def __init__(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Serial(self) -> LablinkSerialDto: ...
    @Serial.setter
    def Serial(self, value: LablinkSerialDto) -> LablinkSerialDto: ...
    @property
    def Version(self) -> str: ...
    @Version.setter
    def Version(self, value: str) -> str: ...


class InstrumentClaimDto(MultiInstrumentBaseDto):
    def __init__(self, instruments: IReadOnlyList_1[LablinkInstrumentInfo], allInstrumentsMustSucceed: bool = ...) -> None: ...
    @property
    def AllInstrumentsMustSucceed(self) -> bool: ...
    @AllInstrumentsMustSucceed.setter
    def AllInstrumentsMustSucceed(self, value: bool) -> bool: ...
    @property
    def InstrumentProperties(self) -> Dictionary_2[str, typing.Any]: ...
    @InstrumentProperties.setter
    def InstrumentProperties(self, value: Dictionary_2[str, typing.Any]) -> Dictionary_2[str, typing.Any]: ...


class InstrumentFirmwareDto:
    def __init__(self) -> None: ...
    @property
    def Major(self) -> int: ...
    @Major.setter
    def Major(self, value: int) -> int: ...
    @property
    def Minor(self) -> int: ...
    @Minor.setter
    def Minor(self, value: int) -> int: ...
    @property
    def Patch(self) -> int: ...
    @Patch.setter
    def Patch(self, value: int) -> int: ...
    @property
    def ReleaseDate(self) -> DateTime: ...
    @ReleaseDate.setter
    def ReleaseDate(self, value: DateTime) -> DateTime: ...
    @property
    def ReleaseType(self) -> str: ...
    @ReleaseType.setter
    def ReleaseType(self, value: str) -> str: ...


class InstrumentHardwareVersionDto:
    def __init__(self) -> None: ...
    @property
    def Major(self) -> int: ...
    @Major.setter
    def Major(self, value: int) -> int: ...
    @property
    def Minor(self) -> int: ...
    @Minor.setter
    def Minor(self, value: int) -> int: ...


class InstrumentInfoDto:
    def __init__(self) -> None: ...
    @property
    def ClaimOwnerUsername(self) -> str: ...
    @ClaimOwnerUsername.setter
    def ClaimOwnerUsername(self, value: str) -> str: ...
    @property
    def CustomInstrumentName(self) -> str: ...
    @CustomInstrumentName.setter
    def CustomInstrumentName(self, value: str) -> str: ...
    @property
    def DefaultInstrumentName(self) -> str: ...
    @DefaultInstrumentName.setter
    def DefaultInstrumentName(self, value: str) -> str: ...
    @property
    def FirmwareVersion(self) -> InstrumentFirmwareDto: ...
    @FirmwareVersion.setter
    def FirmwareVersion(self, value: InstrumentFirmwareDto) -> InstrumentFirmwareDto: ...
    @property
    def HardwareVersion(self) -> InstrumentHardwareVersionDto: ...
    @HardwareVersion.setter
    def HardwareVersion(self, value: InstrumentHardwareVersionDto) -> InstrumentHardwareVersionDto: ...
    @property
    def IsInErrorState(self) -> bool: ...
    @IsInErrorState.setter
    def IsInErrorState(self, value: bool) -> bool: ...
    @property
    def IsMeasuring(self) -> bool: ...
    @IsMeasuring.setter
    def IsMeasuring(self, value: bool) -> bool: ...
    @property
    def Model(self) -> str: ...
    @Model.setter
    def Model(self, value: str) -> str: ...
    @property
    def MultiChannelId(self) -> str: ...
    @MultiChannelId.setter
    def MultiChannelId(self, value: str) -> str: ...
    @property
    def MultiChannelIndex(self) -> int: ...
    @MultiChannelIndex.setter
    def MultiChannelIndex(self, value: int) -> int: ...
    @property
    def Serial(self) -> LablinkSerialDto: ...
    @Serial.setter
    def Serial(self, value: LablinkSerialDto) -> LablinkSerialDto: ...


class LablinkSerialDto:
    def __init__(self) -> None: ...
    @property
    def Serial(self) -> str: ...
    @Serial.setter
    def Serial(self, value: str) -> str: ...


class MeasurementInfoResponseDto:
    def __init__(self) -> None: ...
    @property
    def CreatedOn(self) -> DateTimeOffset: ...
    @CreatedOn.setter
    def CreatedOn(self, value: DateTimeOffset) -> DateTimeOffset: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def MethodTechnique(self) -> str: ...
    @MethodTechnique.setter
    def MethodTechnique(self, value: str) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def TotalPointCount(self) -> int: ...
    @TotalPointCount.setter
    def TotalPointCount(self, value: int) -> int: ...
    @property
    def UploadedByUserName(self) -> str: ...
    @UploadedByUserName.setter
    def UploadedByUserName(self, value: str) -> str: ...


class MeasurementInstrumentInfoDto:
    def __init__(self) -> None: ...
    @property
    def FirmwareVersion(self) -> InstrumentFirmwareDto: ...
    @FirmwareVersion.setter
    def FirmwareVersion(self, value: InstrumentFirmwareDto) -> InstrumentFirmwareDto: ...
    @property
    def HardwareVersion(self) -> InstrumentHardwareVersionDto: ...
    @HardwareVersion.setter
    def HardwareVersion(self, value: InstrumentHardwareVersionDto) -> InstrumentHardwareVersionDto: ...
    @property
    def Model(self) -> str: ...
    @Model.setter
    def Model(self, value: str) -> str: ...
    @property
    def MultiChannelId(self) -> str: ...
    @MultiChannelId.setter
    def MultiChannelId(self, value: str) -> str: ...
    @property
    def MultiChannelIndex(self) -> int: ...
    @MultiChannelIndex.setter
    def MultiChannelIndex(self, value: int) -> int: ...
    @property
    def Serial(self) -> InstrumentSerialDto: ...
    @Serial.setter
    def Serial(self, value: InstrumentSerialDto) -> InstrumentSerialDto: ...


class MeasurementResponseDto:
    def __init__(self) -> None: ...
    @property
    def CreatedOn(self) -> DateTimeOffset: ...
    @CreatedOn.setter
    def CreatedOn(self, value: DateTimeOffset) -> DateTimeOffset: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def Instrument(self) -> MeasurementInstrumentInfoDto: ...
    @Instrument.setter
    def Instrument(self, value: MeasurementInstrumentInfoDto) -> MeasurementInstrumentInfoDto: ...
    @property
    def Method(self) -> MethodResponseDto: ...
    @Method.setter
    def Method(self, value: MethodResponseDto) -> MethodResponseDto: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def RawDataSets(self) -> List_1[RawDataSetResponseDto]: ...
    @RawDataSets.setter
    def RawDataSets(self, value: List_1[RawDataSetResponseDto]) -> List_1[RawDataSetResponseDto]: ...


class MethodParametersDto(Dictionary_2[str, str]):
    def __init__(self, parameters: IReadOnlyCollection_1[KeyValuePair_2[str, str]]) -> None: ...
    @property
    def Capacity(self) -> int: ...
    @property
    def Comparer(self) -> IEqualityComparer_1[str]: ...
    @property
    def Count(self) -> int: ...
    @property
    def Keys(self) -> Dictionary_2.KeyCollection_2[str, str]: ...
    @property
    def Values(self) -> Dictionary_2.ValueCollection_2[str, str]: ...
    # Skipped AddValue due to it being static, abstract and generic.

    AddValue : AddValue_MethodGroup
    class AddValue_MethodGroup:
        @typing.overload
        def __call__(self, key: str, value: float) -> None:...
        @typing.overload
        def __call__(self, key: str, value: str) -> None:...
        # Method AddValue(key : String, value : Boolean) was skipped since it collides with above method
        @typing.overload
        def __call__(self, key: str, value: CurrentRange) -> None:...

    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...


class MethodResponseDto:
    def __init__(self) -> None: ...
    @property
    def CreatedOn(self) -> DateTimeOffset: ...
    @CreatedOn.setter
    def CreatedOn(self, value: DateTimeOffset) -> DateTimeOffset: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def Parameters(self) -> Dictionary_2[str, str]: ...
    @Parameters.setter
    def Parameters(self, value: Dictionary_2[str, str]) -> Dictionary_2[str, str]: ...
    @property
    def Technique(self) -> str: ...
    @Technique.setter
    def Technique(self, value: str) -> str: ...


class MultiInstrumentBaseDto:
    @property
    def AllInstrumentsMustSucceed(self) -> bool: ...
    @AllInstrumentsMustSucceed.setter
    def AllInstrumentsMustSucceed(self, value: bool) -> bool: ...
    @property
    def InstrumentProperties(self) -> Dictionary_2[str, typing.Any]: ...
    @InstrumentProperties.setter
    def InstrumentProperties(self, value: Dictionary_2[str, typing.Any]) -> Dictionary_2[str, typing.Any]: ...


class MultiInstrumentResponseBaseDto:
    def __init__(self) -> None: ...
    @property
    def Serial(self) -> str: ...
    @Serial.setter
    def Serial(self, value: str) -> str: ...
    @property
    def StatusCode(self) -> int: ...
    @StatusCode.setter
    def StatusCode(self, value: int) -> int: ...


class RawDataSetResponseDto:
    def __init__(self) -> None: ...
    @property
    def CreatedOn(self) -> DateTimeOffset: ...
    @CreatedOn.setter
    def CreatedOn(self, value: DateTimeOffset) -> DateTimeOffset: ...
    @property
    def DataArrays(self) -> List_1[DataArrayResponseDto]: ...
    @DataArrays.setter
    def DataArrays(self, value: List_1[DataArrayResponseDto]) -> List_1[DataArrayResponseDto]: ...
    @property
    def DataSetId(self) -> Guid: ...
    @DataSetId.setter
    def DataSetId(self, value: Guid) -> Guid: ...
    @property
    def PointCount(self) -> int: ...
    @PointCount.setter
    def PointCount(self, value: int) -> int: ...


class RegisterDto(UserCredentialDto):
    def __init__(self) -> None: ...
    @property
    def Password(self) -> str: ...
    @Password.setter
    def Password(self, value: str) -> str: ...
    @property
    def UserName(self) -> str: ...
    @UserName.setter
    def UserName(self, value: str) -> str: ...


class StartMeasurementDto(MultiInstrumentBaseDto):
    def __init__(self, instruments: IReadOnlyList_1[LablinkInstrumentInfo], method: Method, allInstrumentsMustSucceed: bool = ...) -> None: ...
    @property
    def AllInstrumentsMustSucceed(self) -> bool: ...
    @AllInstrumentsMustSucceed.setter
    def AllInstrumentsMustSucceed(self, value: bool) -> bool: ...
    @property
    def InstrumentProperties(self) -> Dictionary_2[str, typing.Any]: ...
    @InstrumentProperties.setter
    def InstrumentProperties(self, value: Dictionary_2[str, typing.Any]) -> Dictionary_2[str, typing.Any]: ...
    @property
    def MethodParameters(self) -> MethodParametersDto: ...
    @MethodParameters.setter
    def MethodParameters(self, value: MethodParametersDto) -> MethodParametersDto: ...
    @property
    def Technique(self) -> str: ...
    @Technique.setter
    def Technique(self, value: str) -> str: ...


class StartMeasurementResponseDto(MultiInstrumentResponseBaseDto):
    def __init__(self) -> None: ...
    @property
    def Result(self) -> Guid: ...
    @Result.setter
    def Result(self, value: Guid) -> Guid: ...
    @property
    def Serial(self) -> str: ...
    @Serial.setter
    def Serial(self, value: str) -> str: ...
    @property
    def StatusCode(self) -> int: ...
    @StatusCode.setter
    def StatusCode(self, value: int) -> int: ...


class UserCredentialDto:
    def __init__(self) -> None: ...
    @property
    def Password(self) -> str: ...
    @Password.setter
    def Password(self, value: str) -> str: ...
    @property
    def UserName(self) -> str: ...
    @UserName.setter
    def UserName(self, value: str) -> str: ...
