from __future__ import annotations

METHODSCRIPT_CAPABILITIES = {
    # 0: 'RESERVED',
    1: 'var',
    2: 'array',
    3: 'store_var',
    4: 'copy_var',
    5: 'add_var',
    6: 'sub_var',
    7: 'mul_var',
    8: 'div_var',
    9: 'set_e',
    10: 'set_int',
    11: 'await_int',
    12: 'wait',
    13: 'loop',
    14: 'endloop',
    15: 'breakloop',
    16: 'if',
    17: 'else',
    18: 'elseif',
    19: 'endif',
    20: 'get_time',
    21: 'meas',
    # 22: 'RESERVED',
    23: 'meas_loop_lsv',
    24: 'meas_loop_cv',
    25: 'meas_loop_dpv',
    26: 'meas_loop_swv',
    27: 'meas_loop_npv',
    28: 'meas_loop_ca',
    29: 'meas_loop_pad',
    30: 'meas_loop_ocp',
    31: 'meas_loop_eis',
    32: 'set_autoranging',
    33: 'pck_start',
    34: 'pck_add',
    35: 'pck_end',
    36: 'set_max_bandwidth',
    37: 'set_cr',
    38: 'cell_on',
    39: 'cell_off',
    40: 'set_pgstat_mode',
    41: 'send_string',
    42: 'set_pgstat_chan',
    43: 'set_gpio_cfg',
    44: 'set_gpio_pullup',
    45: 'set_gpio',
    46: 'get_gpio',
    47: 'set_pot_range',
    # 48: 'RESERVED',
    49: 'set_poly_we_mode',
    50: 'file_open',
    51: 'file_close',
    52: 'set_script_output',
    53: 'array_get',
    54: 'array_set',
    55: 'i2c_config',
    56: 'i2c_read_byte',
    57: 'i2c_write_byte',
    58: 'i2c_read',
    59: 'i2c_write',
    60: 'i2c_write_read',
    61: 'hibernate',
    62: 'abort',
    63: 'timer_start',
    64: 'timer_get',
    65: 'set_range',
    66: 'set_range_minmax',
    67: 'meas_loop_cp',
    68: 'set_i',
    69: 'meas_loop_lsp',
    70: 'meas_loop_geis',
    71: 'int_to_float',
    72: 'float_to_int',
    73: 'bit_and_var',
    74: 'bit_or_var',
    75: 'bit_xor_var',
    76: 'bit_lsl_var',
    77: 'bit_lsr_var',
    78: 'bit_inv_var',
    79: 'set_channel_sync',
    80: 'set_acquisition_frac',
    81: 'mux_config',
    82: 'mux_get_channel_count',
    83: 'mux_set_channel',
    84: 'set_gpio_msk',
    85: 'get_gpio_msk',
    86: 'set_e_aux',
    # 87: 'RESERVED',
    88: 'set_ir_comp',
    # 89: 'RESERVED',
    90: 'meas_fast_cv',
    91: 'set_acquisition_frac_autoadjust',
    92: 'alter_vartype',
    93: 'meas_loop_acv',
    94: 'meas_ms_eis',
    95: 'meas_fast_ca',
    96: 'mod_var',
    97: 'notify_led',
    98: 'set_scan_dir',
    99: 'meas_loop_ca_alt_mux',
    100: 'meas_loop_cp_alt_mux',
    101: 'meas_loop_ocp_alt_mux',
    102: 'smooth',
    103: 'peak_detect',
    104: 'set_bipot_mode',
    105: 'set_bipot_potential',
    106: 'meas_loop_eis_dual',
    107: 'rtc_get',
    # 108: 'RESERVED',
    109: 'beep',
    110: 'battery_perc',
    111: 'get_progress',
    112: 'pow_var',
    113: 'subarray',
    114: 'log_var',
    115: 'linear_fit',
    116: 'mean',
    117: 'trim_enable',
    118: 'meas_scp',
    119: 'display_text',
    120: 'display_btns',
    121: 'display_clear',
    122: 'display_progress',
    123: 'display_icon',
    124: 'display_draw',
    125: 'display_inp_num',
    126: 'display_scroll_add',
    127: 'display_scroll_get',
    128: 'display_keyboard',
    129: 'qr_scan',
    130: 'str',
    131: 'store_str',
    132: 'load_saved_start',
    133: 'load_saved_end',
    134: 'load_saved_var',
    135: 'load_saved_str',
    136: 'save_var',
    137: 'save_str',
    138: 'float_to_int_round',
    139: 'display_filebrowse',
    140: 'droplet_detect_loop',
    141: 'str_find',
    142: 'str_length',
    143: 'str_parse_float',
    144: 'str_parse_int',
}

COMMUNICATION_CAPABILITIES = {
    # 0: 'RESERVED',
    1: 't',  # Get firmware version
    # 2 - 31: 'RESERVED',
    32: 'CC',  # Get runtime capabilities
    33: 'CM',  # Get MethodSCRIPT capabilities
    34: 'S',  # Set register
    35: 'G',  # Get register
    36: 'l',  # Load MethodSCRIPT
    37: 'r',  # Run loaded MethodSCRIPT
    38: 'e',  # Execute (= load and run) MethodSCRIPT
    39: 'dlfw',  # Enter bootloader
    # 40 - 42: 'RESERVED',
    43: 'Fmscr',  # Store loaded MethodSCRIPT to NVM
    44: 'Lmscr',  # Load MethodSCRIPT from NVM
    # 45 - 47: 'RESERVED',
    48: 'i',  # Get serial number
    49: 'v',  # Get MethodSCRIPT version
    # 50: 'RESERVED',
    51: 'fs_dir',  # Get directory listing
    52: 'fs_get',  # Read file
    53: 'fs_put',  # Write file
    54: 'fs_del',  # Delete file or directory
    55: 'fs_info',  # Get file system information
    56: 'fs_format',  # Format storage device
    57: 'fs_mount',  # Mount file system
    58: 'fs_unmount',  # Unmount file system
    59: 'fs_clear',  # Clear file system
    60: 'm',  # Get multi-channel serial number
    61: 'RESERVED',
    62: 'l_fs',  # Load MethodSCRIPT from file
    63: 'e_fs',  # Execute (= load and run) MethodSCRIPT from file
    64: 'sfs_put',  # Write file with cryptographic verification
    65: 'sfs_del',  # Delete file with cryptographic verification
    66: 'sfs_format',  # Format filesystem with cryptographic verification
    67: 'sfs_clear',  # Clear filesystem with cryptographic verification
    68: 'comm_lock',  # Comm Lock
    69: 'comm_unlock',  # Comm Unlock
    # 70 - 95: 'RESERVED',
    96: 'h',  # Halt script execution
    97: 'H',  # Resume script execution
    98: 'Z',  # Abort script execution
    99: 'Y',  # Abort measurement loop
    # 100: 'RESERVED',
    101: 'R',  # Reverse CV sweep
}

METHODSCRIPT_ERRORS = {
    '0001': 'An unspecified error has occurred',
    '0002': 'An invalid VarType has been used',
    '0003': 'The command was not recognized',
    '0004': 'Unknown register',
    '0005': 'Register is read-only',
    '0006': 'Communication mode invalid',
    '0007': 'An argument has an unexpected value',
    '0008': 'Command exceeds maximum length',
    '0009': 'The command has timed out',
    '000B': 'Cannot reserve the memory needed for this var',
    '000C': 'No script has been loaded',
    '000E': 'An overflow has occurred while averaging a measured value',
    '000F': 'The given potential is not valid',
    '0010': 'A variable has become either "NaN" or "inf"',
    '0011': 'The input frequency is invalid',
    '0012': 'The input amplitude is invalid',
    '0014': 'Cannot perform OCP measurement when cell on',
    '0015': 'CRC invalid',
    '0016': 'An error has occurred while reading / writing flash',
    '0017': 'The specified flash address is not valid for this device',
    '0018': 'The device settings have been corrupted',
    '0019': 'Authentication error',
    '001A': 'Calibration invalid',
    '001B': 'This command or part of this command is not supported by the current device',
    '001C': 'Step Potential must at least 1 DAC LSB for this technique',
    '001D': 'Pulse Potential must at least 1 DAC LSB for this technique',
    '001E': 'Amplitude must at least 1 DAC LSB this technique',
    '001F': 'Product is not licensed for this technique',
    '0020': 'Cannot have more than one high speed and/or max range mode enabled',
    '0021': 'The specified PGStat mode is not supported',
    '0022': 'Channel set to be used as Poly WE is not configured as Poly WE',
    '0023': 'Command is invalid for the selected PGStat mode',
    '0024': 'The maximum number of vars to measure has been exceeded',
    '0025': 'The specified PAD mode is unknown',
    '0026': 'An error has occurred during a file operation',
    '0027': 'Cannot open file, a file with this name already exists',
    '0028': 'Variable divided by zero',
    '0029': 'GPIO pin mode is not known by the device',
    '002B': 'CRC of received line was incorrect (CRC16-ext)',
    '002C': 'ID of received line was not the expected value (CRC16-ext)',
    '002D': 'Received line was too short to extract a header (CRC16-ext)',
    '002E': 'Settings are not initialized',
    '002F': 'Channel is not available for this device',
    '0030': 'Calibration process has failed',
    '0032': 'Critical cell overload, aborting measurement to prevent damage.',
    '0033': 'FLASH ECC error has occurred',
    '0034': 'Flash program operation failed',
    '0035': 'Flash Erase operation failed',
    '0036': 'Flash page/block is locked',
    '0037': 'Flash write operation on protected memory',
    '0038': 'Flash is busy executing last command.',
    '0039': 'Operation failed because block was marked as bad',
    '003A': 'The specified address is not valid',
    '003B': 'An error has occurred while attempting to mount the filesystem',
    '003C': 'An error has occurred while attempting to format the filesystem memory',
    '003D': 'A timeout has occurred during SPI communication',
    '003E': 'A timeout has occurred somewhere',
    '003F': 'The calibrations registers are locked, write actions not allowed.',
    '0040': 'Memory module not supported.',
    '0041': 'Flash memory format not recognized or supported.',
    '0042': 'This register is locked for current permission level.',
    '0043': 'Register is write-only',
    '0044': 'Command requires additional initialization',
    '0045': 'Configuration not valid for this command',
    '0046': 'The multiplexer was not found.',
    '0047': 'The filesystem has to be mounted to complete this action.',
    '0048': 'This device is not a multi-device, no serial available.',
    '004A': 'MCU register access is not allowed, only RAM and peripherals are accessible.',
    '004B': 'Runtime (comm) command argument too short to be valid.',
    '004C': 'Runtime (comm) command argument has an invalid format.',
    '004E': 'Hibernate wake up source is invalid',
    '004F': 'Hibernate requires at least one wake up source, none was given.',
    '0050': 'Wake pin for hibernate not configured as input',
    '0051': 'The code provided to the permission register was not valid.',
    '0052': 'An overrun error occurred on a communication interface (e.g. UART).',
    '0053': 'Argument length incorrect for this register.',
    '0055': 'The GPIO pins requested to change do not exist on this instrument.',
    '0056': 'The selected GPIO pin mode is not allowed (by NVM config or device type).',
    '0057': 'The on-board flash module has timed out.',
    '0058': 'Timing error during fast measurement (possibly caused by communication).',
    '005A': 'The instrument cannot meet the requested measurement timing.',
    '005B': 'The variable type is already being measured.',
    '006D': 'The COMM command expected an hexadecimal value, but received something else.',
    '006E': 'The COMM command expected a decimal value, but received something else.',
    '0071': 'The provided key does not fit the lock on this register.',
    '0072': 'I2C port expander did not acknowledge a command',
    '0073': 'Filesystem module not supported',
    '0074': 'The IP address is not available (yet).',
    '007A': 'There is no measurement channel left for the requested measurement.',
    '007B': 'Temperature measurements during EIS with > 8 kHz are not supported.',
    '007C': 'The specified mode is unknown',
    '007D': 'The ADXL367 did not acknowledge an I2C command',
    '007E': 'An unexpected error occurred during an I2C operation.',
    '007F': 'I2C bus timeout during I2C operation (probably caused by I2C target device).',
    '0080': 'The CE is oscillating.',
    '0082': 'Operation requires system warnings to be cleared.',
    '0083': 'Filesystem operations are not supported on this device.',
    '0084': 'The requested variable type does not support ranging.',
    '0085': 'The selected GPIO pin does not support hardware synchronization.',
    '0086': 'Hardware select must be disabled before the role pin can be disabled.',
    '0087': 'The role pin must be configured before the hardware select can be enabled',
    '0088': 'The instrument has reserved this GPIO pin to be controlled by hardware (e.g. file system or HW-sync).',
    '0089': 'This GPIO pin cannot be unlocked, as it was not locked in the first place',
    '008A': 'This GPIO pin can only be used for interfacing with a specific external memory',
    '008B': 'The BiPot should be disabled.',
    '008C': 'iR compensation should be disabled.',
    '008D': 'The key provided for the reset command is incorrect.',
    '008E': 'The SPI interface is not configured while it is required for the filesystem',
    '008F': 'The SPI interface requires the SPI pins to be configured to `peri 1`',
    '0090': 'The GPIO pin cannot be mapped to this signal as it is used by the hw_sync_iterate signal',
    '0091': 'The GPIO pin cannot be mapped to this signal as it is used by the hw_sync_start signal',
    '0092': 'The GPIO pin cannot be mapped to this signal as it is used by the hw_sync_role signal',
    '0093': 'The GPIO pin cannot be mapped to this signal as it is used by the led_red signal',
    '0094': 'The GPIO pin cannot be mapped to this signal as it is used by the led_green signal',
    '0095': 'The GPIO pin cannot be mapped to this signal as it is used by the led_blue signal',
    '0097': 'The requested signal is currently unavailable to a GPIO',
    '0098': 'The configuration set using the Peripheral configuration (`01`) register is invalid',
    '0099': 'Filesystem file is corrupt',
    '009A': 'Filesystem failed to format',
    '009B': 'Filesystem I/O error',
    '009C': 'Filesystem didn’t have enough memory to perform the operation',
    '009D': 'Filesystem path was too long to handle',
    '009E': 'Filesystem the path was not valid',
    '009F': 'Filesystem could not find the file specified',
    '00A0': 'Filesystem FM not supported',
    '00A1': 'Filesystem doesn’t have a listing',
    '00A2': 'Filesystem is not initialized',
    '00A3': 'Filesystem file is open, but it should not have been',
    '00A4': 'Filesystem file is not open',
    '00A5': 'Filesystem does not support this feature',
    '00A6': 'Filesystem expected something which is not true.',
    '00A7': 'Filesystem could not find the path',
    '00A8': 'Access denied due to prohibited access or directory full',
    '00A9': 'The file/directory object is invalid',
    '00AA': 'The physical drive is write protected',
    '00AB': 'The logical drive number is invalid',
    '00AC': 'There is no valid filesystem volume',
    '00AD': 'The format operation was aborted due to any problem',
    '00AE': 'The operation is rejected according to the file sharing policy',
    '00AF': 'Working buffer could not be allocated',
    '00B0': 'Too many files opened at once by filesystem',
    '00B1': 'Parameter given to the filesystem is invalid',
    '00B2': 'The file mode is invalid (should be read-only, new, append, overwrite).',
    '00B3': 'The pin mode required for the LED mapping is not allowed for this pin',
    '00B4': 'The pin mode required for the HW-sync role is not allowed for this pin',
    '00B5': 'The pin mode required for the HW-sync start mapping is not allowed for this pin',
    '00B6': 'Use of the encrypted filesystem failed',
    '00B7': 'The user key is not in a valid state for this command',
    '00B8': 'The communications protocol is not in valid lock state for this command',
    '00B9': 'Cannot reserve the memory needed for this string',
    '00BA': 'Writing to the GPIO pin requires that it is configured as output',
    '00BB': 'Reading a GPIO pin requires that it is configured as input',
    '00BC': 'Pull-up resistors can only be enabled on inputs',
    '00BD': 'The requested multiplexer is not valid for this instrument',
    '00BE': 'The requested MethodSCRIPT pin is not configured (may be unmapped)',
    '00BF': 'The signal hw_sync_iterate is already mapped to a GPIO pin, please unmap first',
    '00C0': 'The signal hw_sync_start is already mapped to a GPIO pin, please unmap first',
    '00C1': 'The signal hw_sync_role is already mapped to a GPIO pin, please unmap first',
    '00C2': 'The signal led_red is already mapped to a GPIO pin, please unmap first',
    '00C3': 'The signal led_green is already mapped to a GPIO pin, please unmap first',
    '00C4': 'The signal led_blue is already mapped to a GPIO pin, please unmap first',
    '00C5': 'The hardware synchronization mode is not supported by the instrument',
    '00C6': 'The HW sync is configured while the iterate signal is currently unavailable to a GPIO pin',
    '00C7': 'The HW sync is configured while the start signal is currently unavailable to a GPIO pin',
    '00C8': 'The HW sync is configured with HW-select while the role signal is currently unavailable to a GPIO pin',
    '00C9': 'The GPIO pin cannot be mapped to this signal as it is used by the we0_enable signal',
    '00CA': 'The GPIO pin cannot be mapped to this signal as it is used by the ce0_enable signal',
    '00CB': 'The GPIO pin cannot be mapped to this signal as it is used by the we1_enable signal',
    '00CC': 'The GPIO pin cannot be mapped to this signal as it is used by the ce1_enable signal',
    '00CD': 'The GPIO pin cannot be mapped to this signal as it is used by the user_i2c_scl signal',
    '00CE': 'The GPIO pin cannot be mapped to this signal as it is used by the user_i2c_sda signal',
    '00CF': 'The GPIO pin cannot be mapped to this signal as it is used by the spi_clk signal',
    '00D0': 'The GPIO pin cannot be mapped to this signal as it is used by the spi_mosi signal',
    '00D1': 'The GPIO pin cannot be mapped to this signal as it is used by the spi_miso signal',
    '00D2': 'The GPIO pin cannot be mapped to this signal as it is used by the spi_cs signal',
    '00D3': 'The signal we0_enable is already mapped to a GPIO pin, please unmap first',
    '00D4': 'The signal ce0_enable is already mapped to a GPIO pin, please unmap first',
    '00D5': 'The signal we1_enable is already mapped to a GPIO pin, please unmap first',
    '00D6': 'The signal ce1_enable is already mapped to a GPIO pin, please unmap first',
    '00D7': 'The signal user_i2c_scl is already mapped to a GPIO pin, please unmap first',
    '00D8': 'The signal user_i2c_sda is already mapped to a GPIO pin, please unmap first',
    '00D9': 'The signal spi_clk is already mapped to a GPIO pin, please unmap first',
    '00DA': 'The signal spi_mosi is already mapped to a GPIO pin, please unmap first',
    '00DB': 'The signal spi_miso is already mapped to a GPIO pin, please unmap first',
    '00DC': 'The signal spi_cs is already mapped to a GPIO pin, please unmap first',
    '00DD': 'The GPIO pin does not support signal hw_sync_iterate',
    '00DE': 'The GPIO pin does not support signal hw_sync_start',
    '00DF': 'The GPIO pin does not support signal hw_sync_role',
    '00E0': 'The GPIO pin does not support signal led_red',
    '00E1': 'The GPIO pin does not support signal led_green',
    '00E2': 'The GPIO pin does not support signal led_blue',
    '00E3': 'The GPIO pin does not support signal we0_enable',
    '00E4': 'The GPIO pin does not support signal ce0_enable',
    '00E5': 'The GPIO pin does not support signal we1_enable',
    '00E6': 'The GPIO pin does not support signal ce1_enable',
    '00E7': 'The GPIO pin does not support signal spi_clk',
    '00E8': 'The GPIO pin does not support signal spi_mosi',
    '00E9': 'The GPIO pin does not support signal spi_miso',
    '00EA': 'The GPIO pin does not support signal spi_cs',
    '00EB': 'The GPIO pin does not support signal MethodSCRIPT GPIO 0',
    '00EC': 'The GPIO pin does not support signal MethodSCRIPT GPIO 1',
    '00ED': 'The GPIO pin does not support signal MethodSCRIPT GPIO 2',
    '00EE': 'The GPIO pin does not support signal MethodSCRIPT GPIO 3',
    '00EF': 'The GPIO pin does not support signal MethodSCRIPT GPIO 4',
    '00F0': 'The GPIO pin does not support signal MethodSCRIPT GPIO 5',
    '00F1': 'The GPIO pin does not support signal MethodSCRIPT GPIO 6',
    '00F2': 'The GPIO pin does not support signal MethodSCRIPT GPIO 7',
    # '00F2': 'The GPIO pin does not support signal MethodSCRIPT GPIO 8',
    '00F3': 'The GPIO pin does not support signal MethodSCRIPT GPIO 9',
    '00F4': 'The signal hw_sync_iterate is currently unavailable to a GPIO pin',
    '00F5': 'The signal hw_sync_start is currently unavailable to a GPIO pin',
    '00F6': 'The signal hw_sync_role is currently unavailable to a GPIO pin',
    '00F7': 'The signal led_red is currently unavailable to a GPIO pin',
    '00F8': 'The signal led_green is currently unavailable to a GPIO pin',
    '00F9': 'The signal led_blue is currently unavailable to a GPIO pin',
    '00FA': 'The signal we0_enable is currently unavailable to a GPIO pin',
    '00FB': 'The signal ce0_enable is currently unavailable to a GPIO pin',
    '00FC': 'The signal we1_enable is currently unavailable to a GPIO pin',
    '00FD': 'The signal ce1_enable is currently unavailable to a GPIO pin',
    '00FE': 'The signal spi_clk is currently unavailable to a GPIO pin',
    '00FF': 'The signal spi_mosi is currently unavailable to a GPIO pin',
    '0100': 'The signal spi_miso is currently unavailable to a GPIO pin',
    '0101': 'The signal spi_cs is currently unavailable to a GPIO pin',
    '0102': 'The signal gpio_0 is currently unavailable to a GPIO pin',
    '0103': 'The signal gpio_1 is currently unavailable to a GPIO pin',
    '0104': 'The signal gpio_2 is currently unavailable to a GPIO pin',
    '0105': 'The signal gpio_3 is currently unavailable to a GPIO pin',
    '0106': 'The signal gpio_4 is currently unavailable to a GPIO pin',
    '0107': 'The signal gpio_5 is currently unavailable to a GPIO pin',
    '0108': 'The signal gpio_6 is currently unavailable to a GPIO pin',
    '0109': 'The signal gpio_7 is currently unavailable to a GPIO pin',
    '010A': 'The signal gpio_8 is currently unavailable to a GPIO pin',
    '010B': 'The signal gpio_9 is currently unavailable to a GPIO pin',
    '010C': 'There is nothing left to be read from a data source',
    '010D': 'The GPIO pin does not support signal muxr1 address 0',
    '010E': 'The GPIO pin does not support signal muxr1 address 1',
    '010F': 'The GPIO pin does not support signal muxr1 address 2',
    '0110': 'The GPIO pin does not support signal muxr1 address 3',
    '0111': 'The GPIO pin does not support signal muxr2 en',
    '0112': 'The GPIO pin does not support signal muxr2 clk',
    '0113': 'The GPIO pin does not support signal muxr2 di',
    '0114': 'The GPIO pin does not support signal muxr2 do',
    '0115': 'The GPIO pin does not support signal picomux we 0',
    '0116': 'The GPIO pin does not support signal picomux we 1',
    '0117': 'The GPIO pin does not support signal picomux we 2',
    '0118': 'The GPIO pin does not support signal picomux we 3',
    '0119': 'The GPIO pin does not support signal picomux re ce 0',
    '011A': 'The GPIO pin does not support signal picomux re ce 1',
    '011B': 'The GPIO pin does not support signal picomux re ce 2',
    '011D': 'The GPIO pin does not support signal picomux re ce 3',
    '011E': 'The GPIO pin does not support signal picomux en 0',
    '011F': 'The GPIO pin does not support signal picomux en 1',
    '0120': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr1_address_0 signal',
    '0121': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr1_address_1 signal',
    '0122': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr1_address_2 signal',
    '0123': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr1_address_3 signal',
    '0124': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr2_en signal',
    '0125': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr2_clk signal',
    '0126': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr2_di signal',
    '0127': 'The GPIO pin cannot be mapped to this signal as it is used by the muxr2_do signal',
    '0128': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_we_0 signal',
    # '0128': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_we_1 signal',
    '0129': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_we_2 signal',
    '012A': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_we_3 signal',
    '012B': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_re_ce_0 signal',
    '012C': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_re_ce_1 signal',
    '012D': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_re_ce_2 signal',
    '012E': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_re_ce_3 signal',
    '012F': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_en_0 signal',
    '0130': 'The GPIO pin cannot be mapped to this signal as it is used by the picomux_en_1 signal',
    '0131': 'The signal muxr1_address_0 is currently unavailable to a GPIO pin',
    '0132': 'The signal muxr1_address_1 is currently unavailable to a GPIO pin',
    '0133': 'The signal muxr1_address_2 is currently unavailable to a GPIO pin',
    '0134': 'The signal muxr1_address_3 is currently unavailable to a GPIO pin',
    '0135': 'The signal muxr2_en is currently unavailable to a GPIO pin',
    '0136': 'The signal muxr2_clk is currently unavailable to a GPIO pin',
    '0137': 'The signal muxr2_di is currently unavailable to a GPIO pin',
    '0138': 'The signal muxr2_do is currently unavailable to a GPIO pin',
    '0139': 'The signal picomux_we_0 is currently unavailable to a GPIO pin',
    '013A': 'The signal picomux_we_1 is currently unavailable to a GPIO pin',
    '013B': 'The signal picomux_we_2 is currently unavailable to a GPIO pin',
    '013C': 'The signal picomux_we_3 is currently unavailable to a GPIO pin',
    '013D': 'The signal picomux_re_ce_0 is currently unavailable to a GPIO pin',
    '013E': 'The signal picomux_re_ce_1 is currently unavailable to a GPIO pin',
    '013F': 'The signal picomux_re_ce_2 is currently unavailable to a GPIO pin',
    '0140': 'The signal picomux_re_ce_3 is currently unavailable to a GPIO pin',
    '0141': 'The signal picomux_en_0 is currently unavailable to a GPIO pin',
    '0142': 'The signal picomux_en_1 is currently unavailable to a GPIO pin',
    '0143': 'The static IP is locked if the ethernet interface has been used since boot',
    '0144': 'The parsed string contains an invalid numerical value',
    '4001': 'The script command is unknown',
    '4004': 'An unexpected character was encountered',
    '4005': 'The script is too large for the internal script memory',
    '4008': 'This optional argument is not valid for this command',
    '4009': 'The stored script is generated for an older firmware version and cannot be run',
    '400B': 'Measurement loops cannot be placed inside other measurement loops',
    '400C': 'Command not supported in current situation',
    '400D': 'Scope depth too large',
    '400E': 'The command had an invalid effect on scope depth',
    '400F': 'Array index out of bounds',
    '4010': 'I2C interface was not initialized with i2c_config command',
    '4011': 'This is an error, NAck flag not handled by script',
    '4012': 'Something unexpected went wrong.',
    '4013': 'I2C clock frequency not supported by hardware',
    '4014': 'Non integer SI vars cannot be parsed from hex or binary representation',
    '4016': 'RTC was selected as wake-up source and selected time is not supported',
    '4017': 'Arrays must be the same size but are not',
    '4018': 'The script has ended unexpectedly.',
    '4019': 'The script command is only valid for a multichannel (combined) device',
    '401A': 'The script command cannot be called from within a measurement loop.',
    '401B': 'the packet sequence is called wrong',
    '401C': 'The maximum amounts of variables per packet has been exceeded.',
    '401D': 'The file path is too long for the file system.',
    '401E': 'The volume for the beep command is incorrect',
    '401F': 'The duration for the beep command is not correct',
    '4020': 'A timeout has occurred for one of the script commands',
    '4021': 'The mux is not initialized/configured.',
    '4022': 'Measurement loop timing is too fast to use with multiplexer',
    '4023': 'The script command is only valid for a device with iR compensation',
    '4024': 'The resistance value is to big for the whole autorange range',
    '4025': 'The resistance value is to big for current current range',
    '4026': 'The variable already exists when declared',
    '4027': 'This command requires the cell to be enabled with the cell_on command',
    '4028': 'This command requires the cell to be disabled with the cell_off command',
    '4029': 'The technique requires that at least one step should be made',
    '402A': 'The variable names do not fit in memory anymore, try using shorter names.',
    '402B': 'The variable name did not start with a-z or otherwise contained anything other than a-z, 0-9 and underscore (_).',
    '402C': 'The variable name is too long to be processed.',
    '402D': 'The file mode is invalid.',
    '402E': 'The file mode does not support a counter in the file path.',
    '402F': 'The file path with the maximum counter value already exists.',
    '4030': 'There are too many files open already.',
    '4031': 'The specified multi device type is not valid.',
    '4032': 'Cannot set the potential (or potential range) within the active measurement loop.',
    '4033': 'Cannot set the current (or current range) within the active measurement loop.',
    '4034': 'The used feature is not licensed on this product.',
    '4035': 'The given filter type is unknown or not supported.',
    '4036': 'The given command is only allowed within measurement loops.',
    '4037': 'A computation has resulted in an overflow',
    '4038': 'The array access was not correctly formed',
    '4039': 'The literal argument was not correctly formed',
    '403A': 'The subarray declaration was out of bounds for the source array',
    '403B': 'A file needs to be opened before it can be written to',
    '403C': 'The MethodScript output mode is unknown',
    '403D': 'The MethodScript variable is could not be parsed',
    '403E': 'The file format did not match what was expected',
    '403F': 'The slicing operation was not correctly formed',
    '4040': 'An error occurred while formatting an fstring',
    '4041': 'The requested comparison cannot be performed',
    '4042': 'The requested average count is invalid.',
    '4200': 'MScript argument value cannot be negative for this command',
    '4201': 'MScript argument value cannot be positive for this command',
    '4202': 'MScript argument value cannot be zero for this command',
    '4203': 'MScript argument value must be negative for this command (also not zero)',
    '4204': 'MScript argument value must be positive for this command (also not zero)',
    '4205': 'MScript argument value is outside the allowed bounds for this command',
    '4206': 'MScript argument value cannot be used for this specific instrument',
    '4207': 'MScript argument datatype (float/int) is invalid for this command',
    '4208': 'MScript argument reference was invalid (not a-z)',
    '4209': 'MScript argument variable type is invalid or not supported for this command',
    '420A': 'An unexpected, additional, (optional) MScript argument was provided',
    '420B': 'MScript argument variable is not declared',
    '420C': 'MScript argument is of type var, which is not supported by this command',
    '420D': 'MScript argument is of type literal, which is not supported by this command',
    '420E': 'MScript argument is of type array, which is not supported by this command',
    '420F': 'MScript argument array size is insufficient',
    '4210': 'An f-string contains an opening brace that is never closed',
    '4211': 'MScript argument is an array element, which is not supported by this command',
    '4212': 'MScript argument is an uninitialized string, which is not supported by this command',
    '4213': 'MScript argument is of type string, which is not supported by this command',
    '4214': 'The droplet detect duration is too short',
    '4215': 'MScript argument is an interpolated string, which is not supported by this command',
    '7FFF': 'A fatal error has occurred, the device must be reset',
}
