# generated by datamodel-codegen:
#   filename:  lablink.json
#   timestamp: 2026-09-28T08:42:05+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AuthRequestModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    UserName: str | None = None
    Password: str | None = None


class AuthResponseModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    UserName: str | None = None
    Token: str | None = None


class BiPotMode(Enum):
    Constant = 'Constant'
    Offset = 'Offset'


class CellMode(Enum):
    Unknown = 'Unknown'
    Potentiostatic = 'Potentiostatic'
    Galvanostatic = 'Galvanostatic'


class CellState(Enum):
    Unknown = 'Unknown'
    Off = 'Off'
    On = 'On'


class CustomInstrumentInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    CustomName: str | None = None
    CustomChannel: int | None = None
    CustomGroupName: str | None = None


class CustomUnitDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Unit: str | None = None
    Quantity: str | None = None
    Symbol: str | None = None


class DataValueTypeVariant(Enum):
    Index = 'Index'
    CycleIndex = 'CycleIndex'
    LevelIndex = 'LevelIndex'
    StageIndex = 'StageIndex'
    ScanIndex = 'ScanIndex'
    Timestamp = 'Timestamp'
    Frequency = 'Frequency'
    TimingStatus = 'TimingStatus'
    AppliedCurrent = 'AppliedCurrent'
    MeasuredCurrent = 'MeasuredCurrent'
    ForwardCurrent = 'ForwardCurrent'
    ReverseCurrent = 'ReverseCurrent'
    ACCurrent = 'ACCurrent'
    CurrentRange = 'CurrentRange'
    CurrentReadingStatus = 'CurrentReadingStatus'
    ForwardCurrentReadingStatus = 'ForwardCurrentReadingStatus'
    ReverseCurrentReadingStatus = 'ReverseCurrentReadingStatus'
    MeasuredWE2Current = 'MeasuredWE2Current'
    ForwardWE2Current = 'ForwardWE2Current'
    ReverseWE2Current = 'ReverseWE2Current'
    ACWE2Current = 'ACWE2Current'
    DCWE2Current = 'DCWE2Current'
    WE2CurrentRange = 'WE2CurrentRange'
    WE2CurrentReadingStatus = 'WE2CurrentReadingStatus'
    ForwardWE2CurrentReadingStatus = 'ForwardWE2CurrentReadingStatus'
    ReverseWE2CurrentReadingStatus = 'ReverseWE2CurrentReadingStatus'
    AppliedPotential = 'AppliedPotential'
    AppliedWE2Potential = 'AppliedWE2Potential'
    MeasuredPotential = 'MeasuredPotential'
    MeasuredWECEPotential = 'MeasuredWECEPotential'
    ACPotential = 'ACPotential'
    ACWECEPotential = 'ACWECEPotential'
    DCWECEPotential = 'DCWECEPotential'
    ACRECEPotential = 'ACRECEPotential'
    DCRECEPotential = 'DCRECEPotential'
    PotentialRange = 'PotentialRange'
    PotentialReadingStatus = 'PotentialReadingStatus'
    AuxiliaryPotential = 'AuxiliaryPotential'
    Charge = 'Charge'
    ChargeCapacity = 'ChargeCapacity'
    DischargeCapacity = 'DischargeCapacity'
    AccumulatedCharge = 'AccumulatedCharge'
    ImpedanceReal = 'ImpedanceReal'
    ImpedanceImaginary = 'ImpedanceImaginary'
    ImpedanceMagnitude = 'ImpedanceMagnitude'
    ImpedancePhase = 'ImpedancePhase'
    AdmittanceReal = 'AdmittanceReal'
    AdmittanceImaginary = 'AdmittanceImaginary'
    AdmittanceMagnitude = 'AdmittanceMagnitude'
    CapacitanceReal = 'CapacitanceReal'
    CapacitanceImaginary = 'CapacitanceImaginary'
    CapacitanceSeries = 'CapacitanceSeries'
    ScpValue = 'ScpValue'
    dEdt = 'dEdt'
    Temperature = 'Temperature'
    CustomUnit = 'CustomUnit'
    CoulombicEfficiency = 'CoulombicEfficiency'
    EnergyEfficiency = 'EnergyEfficiency'
    VoltageEfficiency = 'VoltageEfficiency'


class EmptyProperty(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


class FirmwareReleaseType(Enum):
    Unknown = 'Unknown'
    Debug = 'Debug'
    Beta = 'Beta'
    Release = 'Release'


class FirmwareVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Major: int | None = None
    Minor: int | None = None
    Patch: int | None = None
    ReleaseType: FirmwareReleaseType | None = None
    ReleaseDate: datetime | None = None
    CommitId: str | None = None


class FirmwareVersionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Major: int | None = None
    Minor: int | None = None
    Patch: int | None = None
    ReleaseType: str | None = None
    ReleaseDate: datetime | None = None


class HardwareVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Major: int | None = None
    Minor: int | None = None


class HardwareVersionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Major: int | None = None
    Minor: int | None = None


class InstrumentDetailsId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Value: str | None = None
    HasValue: bool | None = None


class InstrumentModel(Enum):
    Uninitialised = 'Uninitialised'
    PalmSens1 = 'PalmSens1'
    PalmSens2 = 'PalmSens2'
    PalmSens3 = 'PalmSens3'
    EmStat1 = 'EmStat1'
    EmStat2 = 'EmStat2'
    EmStat3 = 'EmStat3'
    EmStat3Plus = 'EmStat3Plus'
    EmStat3BiPot = 'EmStat3BiPot'
    PalmSens4 = 'PalmSens4'
    EmStatPico = 'EmStatPico'
    EmStat4HR = 'EmStat4HR'
    EmStat4LR = 'EmStat4LR'
    Nexus = 'Nexus'
    EmStatPicoXR = 'EmStatPicoXR'
    EmStat4XHR = 'EmStat4XHR'
    EmStat4XLR = 'EmStat4XLR'
    Unknown = 'Unknown'


class InstrumentSerial(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Serial: str | None = None


class LablinkNetworkType(Enum):
    Ethernet = 'Ethernet'
    Wifi = 'Wifi'


class LablinkSerial(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Serial: str | None = None


class MainsFrequency(Enum):
    Undefined = 'Undefined'
    Hz50 = 'Hz50'
    Hz60 = 'Hz60'
    DontCare = 'DontCare'


class MeasuringRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Significant: int | None = None
    Exponent: int | None = None
    Value: int | None = None
    Prefix: str | None = None


class MultiChannelRole(Enum):
    Undefined = 'Undefined'
    Standalone = 'Standalone'
    Master = 'Master'
    Slave = 'Slave'


class MyPalmSensEnvironment(Enum):
    Local = 'Local'
    DockerCompose = 'DockerCompose'
    Development = 'Development'
    Testing = 'Testing'
    Staging = 'Staging'
    Production = 'Production'


class SendScriptCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    InstrumentProperties: dict[str, str] | None = None
    AllInstrumentsMustSucceed: bool | None = None


class SetCustomInstrumentNameProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    NewCustomInstrumentName: str | None = None


class SignalTrain(Enum):
    Undefined = 'Undefined'
    LowSpeed = 'LowSpeed'
    HighSpeed = 'HighSpeed'
    MaximumRange = 'MaximumRange'


class SimpleInstrumentsCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    InstrumentProperties: dict[str, EmptyProperty] | None = None
    AllInstrumentsMustSucceed: bool | None = None


class SoftwareResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ApplicationName: str | None = None
    Version: str | None = None


class TagResult(BaseModel):
    Id: UUID | None = None


class TechniqueId(Enum):
    LinearSweepVoltammetry = 'LinearSweepVoltammetry'
    CyclicVoltammetry = 'CyclicVoltammetry'
    FastCyclicVoltammetry = 'FastCyclicVoltammetry'
    ACVoltammetry = 'ACVoltammetry'
    DifferentialPulseVoltammetry = 'DifferentialPulseVoltammetry'
    SquareWaveVoltammetry = 'SquareWaveVoltammetry'
    NormalPulseVoltammetry = 'NormalPulseVoltammetry'
    Chronoamperometry = 'Chronoamperometry'
    MultiStepAmperometry = 'MultiStepAmperometry'
    FastAmperometry = 'FastAmperometry'
    PulsedAmperometricDetection = 'PulsedAmperometricDetection'
    MultiplePulseAmperometry = 'MultiplePulseAmperometry'
    OpenCircuitPotentiometry = 'OpenCircuitPotentiometry'
    Chronopotentiometry = 'Chronopotentiometry'
    MultiStepPotentiometry = 'MultiStepPotentiometry'
    LinearSweepPotentiometry = 'LinearSweepPotentiometry'
    StrippingChronopotentiometry = 'StrippingChronopotentiometry'
    Chronocoulometry = 'Chronocoulometry'
    ElectrochemicalImpedanceSpectroscopy = 'ElectrochemicalImpedanceSpectroscopy'
    GalvanostaticImpedanceSpectroscopy = 'GalvanostaticImpedanceSpectroscopy'
    MixedMode = 'MixedMode'
    MethodScriptSandbox = 'MethodScriptSandbox'
    CorrosionPotential = 'CorrosionPotential'
    CyclicPolarization = 'CyclicPolarization'
    GalvanostaticDetection = 'GalvanostaticDetection'
    LinearPolarization = 'LinearPolarization'
    PotentiostaticDetection = 'PotentiostaticDetection'


class Volt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Value: float | None = None


class WorkflowCommandType(Enum):
    SelectMethod = 'SelectMethod'
    OverrideMethod = 'OverrideMethod'
    SaveMethod = 'SaveMethod'
    RunMeasurement = 'RunMeasurement'
    LoadMeasurement = 'LoadMeasurement'
    GetMeasurement = 'GetMeasurement'
    SaveMeasurement = 'SaveMeasurement'
    ControlCell = 'ControlCell'
    RecordCell = 'RecordCell'
    ControlTrigger = 'ControlTrigger'
    RecordTrigger = 'RecordTrigger'
    AwaitTrigger = 'AwaitTrigger'
    SetMultiplexerChannel = 'SetMultiplexerChannel'
    Repeat = 'Repeat'
    Wait = 'Wait'
    ShowPrompt = 'ShowPrompt'
    CheckCondition = 'CheckCondition'
    AbortProcedure = 'AbortProcedure'
    GotoBlock = 'GotoBlock'
    NewWorkspace = 'NewWorkspace'
    SaveWorkspace = 'SaveWorkspace'
    ClearWorkspace = 'ClearWorkspace'
    CloseWorkspace = 'CloseWorkspace'
    AddCurve = 'AddCurve'
    NewCurve = 'NewCurve'
    EditCurve = 'EditCurve'
    SaveCurve = 'SaveCurve'


class AutoSaveOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Token: str | None = None
    FolderGuid: UUID | None = None
    ProjectId: UUID | None = None
    MyPalmSensEnvironment_1: MyPalmSensEnvironment | None = Field(
        None, alias='MyPalmSensEnvironment'
    )
    LabelsToAppend: list[str] | None = None


class ConfigureInstrumentsProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    MainsFrequency_1: MainsFrequency | None = Field(None, alias='MainsFrequency')
    SignalTrain_1: SignalTrain | None = Field(None, alias='SignalTrain')
    HardwareSyncAllowed: bool | None = None
    MultiChannelRole_1: MultiChannelRole | None = Field(None, alias='MultiChannelRole')


class DataArrayResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    DataArrayId: UUID | None = None
    DataValueType: DataValueTypeVariant | None = None
    DataValuesId: UUID | None = None
    DataArraySizeInBytes: int | None = None
    CustomUnit: CustomUnitDto | None = None


class DiscoveredLablinkResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    IpAddress: str | None = None
    Name: str | None = None
    Serial: str | None = None
    NetworkType: LablinkNetworkType | None = None
    Version: str | None = None


class LablinkConnectTypeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    IpAddress: str | None = None
    NetworkType: LablinkNetworkType | None = None


class LablinkInfoResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Name: str | None = None
    Serial: LablinkSerial | None = None
    Version: str | None = None
    SpecialVersion: str | None = None
    OsVersion: str | None = None
    LablinkModel: str | None = None
    IsMeasuring: bool | None = None


class LicenseSettingsPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    MaximumEISFrequency: float | None = None
    MaximumGEISFrequency: float | None = None
    MaximumAppliedPotential: float | None = None
    MinimumAppliedPotential: float | None = None
    MeasuredPotentialRanges: list[MeasuringRange] | None = None
    SupportsDropDetection: bool | None = None
    HasBiPot: bool | None = None
    HasIrCompensation: bool | None = None
    HasChanges: bool | None = None


class LicenseSettingsPatchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    MaximumEISFrequency: float | None = None
    MaximumGEISFrequency: float | None = None
    MaximumAppliedPotential: float | None = None
    MinimumAppliedPotential: float | None = None
    MeasuredPotentialRanges: list[MeasuringRange] | None = None
    SupportsDropDetection: bool | None = None
    HasBiPot: bool | None = None
    HasIrCompensation: bool | None = None


class MeasurementInstrumentResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Serial: InstrumentSerial | None = None
    Model: InstrumentModel | None = None
    LicenseSettings: LicenseSettingsPatchResult | None = None
    FirmwareVersion: FirmwareVersionResult | None = None
    HardwareVersion: HardwareVersionResult | None = None
    InstrumentDisplayName: str | None = None
    MultiChannelId: str | None = None
    MutliChannelGroupName: str | None = None
    MultiChannelIndex: int | None = None
    ClaimOwnerUsername: str | None = None


class MethodListResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Id: UUID | None = None
    Name: str | None = None
    CreatedOn: AwareDatetime | None = None
    LastModifiedOn: AwareDatetime | None = None
    Technique: TechniqueId | None = None
    UploadedByUserName: str | None = None
    Labels: list[str] | None = None


class MethodResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Id: UUID | None = None
    CreatedOn: AwareDatetime | None = None
    LastModifiedOn: AwareDatetime | None = None
    Technique: TechniqueId | None = None
    Parameters: dict[str, str] | None = None
    UserName: str | None = None


class RawDataSetResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    DataSetId: UUID | None = None
    CreatedOn: AwareDatetime | None = None
    LastModifiedOn: AwareDatetime | None = None
    Name: str | None = None
    PointCount: int | None = None
    DataArrays: list[DataArrayResult] | None = None
    Tags: list[TagResult] | None = None


class SetCustomInstrumentNameCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    InstrumentProperties: dict[str, SetCustomInstrumentNameProperties] | None = None
    AllInstrumentsMustSucceed: bool | None = None


class StartMeasurementCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Technique: TechniqueId | None = None
    MethodParameters: dict[str, str] | None = None
    AutoSaveOptionsResult: AutoSaveOptions | None = None
    CustomGroupInfoResult: CustomInstrumentInfo | None = None


class StartMeasurementProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    CustomGroupInfo: CustomInstrumentInfo | None = None
    AutoSaveOptions_1: AutoSaveOptions | None = Field(None, alias='AutoSaveOptions')


class StartMeasurementsCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    InstrumentProperties: dict[str, StartMeasurementProperties] | None = None
    AllInstrumentsMustSucceed: bool | None = None
    Technique: TechniqueId | None = None
    MethodParameters: dict[str, str] | None = None


class WorkflowCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    FullIndex: str | None = None
    WorkflowType: WorkflowCommandType | None = None


class ConfigureInstrumentsCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    InstrumentProperties: dict[str, ConfigureInstrumentsProperties] | None = None
    AllInstrumentsMustSucceed: bool | None = None


class CurveDataSetResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    DataSetId: UUID | None = None
    CreatedOn: AwareDatetime | None = None
    LastModifiedOn: AwareDatetime | None = None
    Name: str | None = None
    PointCount: int | None = None
    DataArrays: list[DataArrayResult] | None = None
    Tags: list[TagResult] | None = None
    ShowOnSecondaryXAxis: bool | None = None
    ShowOnSecondaryYAxis: bool | None = None
    XAxisDataValueType: str | None = None
    YAxisDataValueType: str | None = None


class InstrumentDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Id: InstrumentDetailsId | None = None
    Serial: InstrumentSerial | None = None
    Model: InstrumentModel | None = None
    LicenseSettings: LicenseSettingsPatch | None = None
    FirmwareVersion_1: FirmwareVersion | None = Field(None, alias='FirmwareVersion')
    HardwareVersion_1: HardwareVersion | None = Field(None, alias='HardwareVersion')
    Name: str | None = None
    Group: str | None = None
    GroupId: str | None = None
    Channel: int | None = None


class MeasurementListResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Id: UUID | None = None
    Name: str | None = None
    UserName: str | None = None
    CreatedOn: AwareDatetime | None = None
    LastModifiedOn: AwareDatetime | None = None
    MethodTechnique: TechniqueId | None = None
    TotalPointCount: int | None = None
    InstrumentDetails_1: InstrumentDetails | None = Field(None, alias='InstrumentDetails')
    Tags: list[TagResult] | None = None


class MeasurementResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Id: UUID | None = None
    CreatedOn: AwareDatetime | None = None
    LastModifiedOn: AwareDatetime | None = None
    Name: str | None = None
    UserName: str | None = None
    Instrument: MeasurementInstrumentResult | None = None
    Method: MethodResult | None = None
    Software: SoftwareResult | None = None
    RawDataSets: list[RawDataSetResult] | None = None
    CurveDataSets: list[CurveDataSetResult] | None = None


class Workflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Name: str | None = None
    Labels: list[str] | None = None
    WorkflowCommands: list[WorkflowCommand] | None = None


class StartWorkflowCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    InstrumentSerials: list[InstrumentSerial] | None = None
    Workflow_1: Workflow | None = Field(None, alias='Workflow')
