from System.Collections.Generic import List_1
from PalmSens.Sdk.Lablink.Example.Lablink.Models.Dtos import DataValueTypes

class DataSetLayoutDto:
    def __init__(self) -> None: ...
    @property
    def DataValueTypes(self) -> List_1[DataValueTypes]: ...
    @DataValueTypes.setter
    def DataValueTypes(self, value: List_1[DataValueTypes]) -> List_1[DataValueTypes]: ...


class InstrumentSerialDto:
    def __init__(self) -> None: ...
    @property
    def Serial(self) -> str: ...
    @Serial.setter
    def Serial(self, value: str) -> str: ...


class UserDetailsDto:
    def __init__(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
