from System.Net.Http import HttpClient, HttpClientHandler, HttpVersionPolicy
from System import Uri, Version, TimeSpan, Guid
from System.Net.Http.Headers import HttpRequestHeaders
from System.Threading.Tasks import Task, Task_1
from System.Collections.Generic import IReadOnlyList_1
from PalmSens.Sdk.Lablink.Example.Lablink.Models import LablinkInstrumentInfo
from System.Threading import CancellationToken
from System.IO import Stream
from PalmSens.Sdk.Lablink.Example.Lablink.Models.Dtos.HttpClient import GetInfoResponseDto, InstrumentInfoDto, MeasurementResponseDto, MeasurementInfoResponseDto, ApiKeyResponseDto, StartMeasurementResponseDto
from PalmSens.Sdk.Lablink.Example.Lablink import LablinkInstrument
from PalmSens import Method

class LablinkHttpClient(HttpClient):
    def __init__(self, handler: HttpClientHandler) -> None: ...
    @property
    def BaseAddress(self) -> Uri: ...
    @BaseAddress.setter
    def BaseAddress(self, value: Uri) -> Uri: ...
    @property
    def DefaultRequestHeaders(self) -> HttpRequestHeaders: ...
    @property
    def DefaultRequestVersion(self) -> Version: ...
    @DefaultRequestVersion.setter
    def DefaultRequestVersion(self, value: Version) -> Version: ...
    @property
    def DefaultVersionPolicy(self) -> HttpVersionPolicy: ...
    @DefaultVersionPolicy.setter
    def DefaultVersionPolicy(self, value: HttpVersionPolicy) -> HttpVersionPolicy: ...
    @property
    def MaxResponseContentBufferSize(self) -> int: ...
    @MaxResponseContentBufferSize.setter
    def MaxResponseContentBufferSize(self, value: int) -> int: ...
    @property
    def Timeout(self) -> TimeSpan: ...
    @Timeout.setter
    def Timeout(self, value: TimeSpan) -> TimeSpan: ...
    def ClaimInstruments(self, instruments: IReadOnlyList_1[LablinkInstrumentInfo], cancellationToken: CancellationToken = ...) -> Task: ...
    def GetDataValues(self, dataSetId: Guid, dataValuesId: Guid) -> Task_1[Stream]: ...
    def GetInfo(self, cancellationToken: CancellationToken = ...) -> Task_1[GetInfoResponseDto]: ...
    def GetInstruments(self, cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[InstrumentInfoDto]]: ...
    def GetMeasurement(self, id: Guid, cancellationToken: CancellationToken = ...) -> Task_1[MeasurementResponseDto]: ...
    def GetMeasurements(self, cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[MeasurementInfoResponseDto]]: ...
    def Login(self, userName: str, password: str, cancellationToken: CancellationToken = ...) -> Task_1[ApiKeyResponseDto]: ...
    def Register(self, userName: str, password: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def StartMeasurements(self, instruments: IReadOnlyList_1[LablinkInstrument], method: Method, cancellationToken: CancellationToken = ...) -> Task_1[IReadOnlyList_1[StartMeasurementResponseDto]]: ...
    def UnclaimInstruments(self, instruments: IReadOnlyList_1[LablinkInstrumentInfo], cancellationToken: CancellationToken = ...) -> Task: ...
