from System import Uri

class LablinkInfo:
    def __init__(self, addressUri: Uri, name: str = ..., serial: str = ..., version: str = ...) -> None: ...
    @property
    def AddressUri(self) -> Uri: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Serial(self) -> str: ...
    @Serial.setter
    def Serial(self, value: str) -> str: ...
    @property
    def Version(self) -> str: ...
    @Version.setter
    def Version(self, value: str) -> str: ...


class LablinkInstrumentInfo:
    def __init__(self, serial: str, model: str, defaultInstrumentName: str, customInstrumentName: str, multiChannelId: str, multiChannelIndex: int, claimOwnerUsername: str, isMeasuring: bool, isInErrorState: bool) -> None: ...
    @property
    def BelongsToMultiChannelInstrument(self) -> bool: ...
    @property
    def ClaimOwnerUsername(self) -> str: ...
    @ClaimOwnerUsername.setter
    def ClaimOwnerUsername(self, value: str) -> str: ...
    @property
    def CustomInstrumentName(self) -> str: ...
    @property
    def DefaultInstrumentName(self) -> str: ...
    @property
    def IsClaimed(self) -> bool: ...
    @property
    def IsInErrorState(self) -> bool: ...
    @property
    def IsMeasuring(self) -> bool: ...
    @IsMeasuring.setter
    def IsMeasuring(self, value: bool) -> bool: ...
    @property
    def Model(self) -> str: ...
    @property
    def MultiChannelId(self) -> str: ...
    @property
    def MultiChannelIndex(self) -> int: ...
    @property
    def Serial(self) -> str: ...
